services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: deps
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    command: pnpm --filter api dev
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
