name: Dependency Review

on:
  pull_request:
    branches: [ main, staging, development ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Client npm audit
        working-directory: ./client
        run: npm audit || echo "Client vulnerabilities found"

      - name: Server npm audit
        working-directory: ./server
        run: npm audit || echo "Server vulnerabilities found"